# Generated by Django 5.2.5 on 2025-09-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=255)),
                ('pseudonimo', models.CharField(max_length=50)),
                ('bio', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre_comuna', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_1',
            fields=[
                ('campo_1_modelo_1', models.AutoField(primary_key=True, serialize=False)),
                ('campo_2_modelo_1', models.CharField(max_length=200)),
                ('campo_3_modelo_1', models.TextField(default='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('departamento', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(max_length=100)),
                ('web', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('digito_verificador', models.CharField(max_length=1)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.biblioteca')),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.biblioteca')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_2',
            fields=[
                ('campo_1_modelo_2', models.AutoField(primary_key=True, serialize=False)),
                ('campo_3_modelo_2', models.DateField()),
                ('campo_4_modelo_2', models.TimeField()),
                ('campo_5_modelo_2', models.DateTimeField()),
                ('campo_6_modelo_2', models.IntegerField()),
                ('campo_7_modelo_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campo_8_modelo_2', models.FloatField()),
                ('campo_9_modelo_2', models.BooleanField()),
                ('campo_10_modelo_2', models.EmailField(max_length=254)),
                ('campo_11_modelo_2', models.URLField()),
                ('campo_12_modelo_2', models.FileField(upload_to='archivos/')),
                ('campo_13_modelo_2', models.ImageField(upload_to='imagenes/')),
                ('campo_2_modelo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.modelo_1')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.nacionalidad'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now=True)),
                ('fecha_devolucion', models.DateField()),
                ('fecha_entrega', models.DateTimeField(auto_now=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca_project.libro')),
            ],
        ),
    ]
