# Generated by Django 5.2.5 on 2025-09-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_2',
            name='campo_2_modelo_2',
        ),
        migrations.DeleteModel(
            name='Modelo_1',
        ),
        migrations.DeleteModel(
            name='Modelo_2',
        ),
    ]
